  version: '3'
  services:
    ui:
      build:
        context   : ../..
        dockerfile: ui/.docker/services/ui/Dockerfile
        args:
          - TERM
      tty: true
      environment:
        DEBUG_COLORS: "true"
        TERM: xterm-256color
        COLORTERM: truecolor
      volumes:
        - .:/usr/src/ui

