  version: '3'
  
  services:
    ui:
      build:
        context   : ../..
        dockerfile: ui/.docker/services/ui/Dockerfile
        # docker/compose is neither very sanely defaulted nor DRY
        args:
          # original USERNAME=automatic in library-scripts/common-debian.sh tries like USERNAME=vscode first,
          # and I need to use HOME as /home/vscode in docker-compose.local.yml services/ui/volumes
          USERNAME: vscode
          
          TERM: ${TERM:-xterm-256color}
          DEBUG_COLORS: "true"
          # truecolor is aka 24bit which I (vike) doubt the macOS iTerm.app I use has - I have only worked with with 1byte=8bit xterm-256color; I have also never used DEBUG_COLORS nor COLORTERM, just found them searching for COLUMNS / ROWS & TERM=xterm-256color issues #cspell:ignore COLORTERM truecolor
          # COLORTERM: truecolor
          
          # next SHOULD not be relevant at build-time
          DISPLAY: host.docker.internal:0
      tty: true
      environment:
        TERM: ${TERM:-xterm-256color}
        DEBUG_COLORS: "true"
        # truecolor is aka 24bit which I (vike) doubt the macOS iTerm.app I use has - I have only worked with with 1byte=8bit xterm-256color; I have also never used DEBUG_COLORS nor COLORTERM, just found them searching for COLUMNS / ROWS & TERM=xterm-256color issues
        # COLORTERM: truecolor
        DISPLAY: host.docker.internal:0 # TODO see launch.json for TODOC
      volumes:
        - "..:/usr/src/ui"
  
